trigger:
  branches:
    include:
      - refs/heads/main
      - refs/tags/*

pool:
  vmImage: 'Ubuntu 16.04'

stages:
- stage: Test
  jobs:
  - job: test_lists
    steps:
    - script: make test
      displayName: 'Test Package Lists'

- stage: Publish
  jobs:
  - job: publish_lists
    steps:
    - script: |
        export AZURE_STORAGE_CONNECTION_STRING=$(AZURE_STORAGE_CONNECTION_STRING)
        make publish
      condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
      displayName: 'Publish Package Lists'
